version: '3'
services:

  postgres:
    build: ./postgres
    restart: always
    image: rspark-postgres
    ports:
      - "5432:5432"     # Postgres
    volumes:
      - rspark_pgdata:/opt/pg-data

  hadoop:
    build: ./hadoop
    restart: always
    image: rhadoop-hadoop
    ports:
      - "9000:9000"     # Hadoop
      - "50070:50070"   # Hadoop UI
    volumes:
      - rhadoop_hadoopdata:/opt/hadoop

  hive:
    build: ./hive
    restart: always
    image: rhadoop-hive
    ports:
      - "10000:10000"
    volumes:
      - rhadoop_hivedata:/opt/hive
    depends_on:
      - hadoop

  rstudio:
    build: ./rstudio
    restart: always
    image: rspark-rstudio
    environment:
      - PASSWORD=rstudiojh
    ports:
      - "8787:8787"     # RStudio UI
      - "8080:8080"
      - "4040:4040"     # Spark Web UI
      - "4041:4041"
      #- "8881:8881"
      #- "8880:8880"
    volumes:
      - rspark_rstudio:/home/rstudio
    depends_on:
      - hadoop
      - hive

volumes:
  rspark_pgdata:
  rhadoop_hadoopdata:
  rhadoop_hivedata:
  rspark_rstudio:
  rspark_sparkdata:
  
