version: '3'
services:

  postgres:
    build: ./postgres
    restart: always
    image: postgres_base:9.6
    ports:
      - "5432:5432"     # Postgres
    volumes:
      - rconnect_pgdata:/opt/pg-data



  rconnect:
    build: ./rstudio
    restart: always
    image: rerocker_base:3.6.3
    environment:
      - PASSWORD=rstudiojh
    ports:
      - "8787:8787"     # RStudio UI
      - "4040:4040"     # Spark Web UI
      - "4041:4041"
    volumes:
      - rconnect_rstudio:/home/rstudio


volumes:
  rconnect_rstudio:
  rconnect_pgdata:

#
#  hadoop:
#    build: ./hadoop
#    restart: always
#    image: rspark-hadoop
#    ports:
#      - "9000:9000"     # Hadoop
#      - "50070:50070"   # Hadoop UI
#    volumes:
#      - rspark_hadoopdata:/opt/hadoop
#
#  hive:
#    build: ./hive
#    restart: always
#    image: rspark-hive
#    ports:
#      - "10000:10000"
#    depends_on:
#      - hadoop
#  rspark_sparkdata:
#    rspark_hadoopdata:
#    depends_on:
#      - hadoop
#      - hive
#
